default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: db/venture_dev

test:
  <<: *default
  database: db/venture_test
  username: postgres
  password:
  port: 5432

production:
  <<: *default
  database: db/venture_production
